baseurl = "/"
languageCode = "es-es"
title = "Portfolio Rey de la Toalla"
theme = "hugo-strata-theme"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
# googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 4

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "El Rey de la Toalla"
	description = "Todo lo que siempre quisiste saber sobre toallas"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = true

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.JPG"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Soy el Rey de la Toalla** Desde hace años me apasionan las toallas. Mi día favorito del año es el 25 de Mayo, que se celebra el dia de la Toalla."
		# The icons will be shown if you enter your username
		twitter = "metametamaking"
		github = "metametamaking-dev"
		copyright = [
			"&copy; Metametamaking",
			"Design: [HTML5 UP](//html5up.net)",
		]


	[params.about]
		hide  = false
		title = "Mi pasión son las toallas y la fotografía. ¡En este sitio encontrarás un montón de ambas!"
		content = "Soy muy fan de las jornadas de trabajo de 16 a 19 con Jaime Altozano, aunque en mi caso, no trabajo. ¡Me dedico a ordenar mis toallas y a crearles un portfolio!

 (A ratos también publico videos en [La Hora Maker](http://www.youtube.com/lahoramaker) o hago sitios como este para practicar y documentar estos procesos :) )"


	[params.portfolio]
		hide  = false
		title = "Mi colección de toallas"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/toalla1.png"
			thumb = "thumbs/toalla1.png"
			title = "Variedad de tonos pastel."
			description = "Siempre hay una para cada ocasión!."

		[[params.portfolio.gallery]]
			image = "fulls/toalla2.png"
			thumb = "thumbs/toalla2.png"
			title = "La tradicional de playa."
			description = "Hace 20 años, estos diseños con bolsillo, causaban furor."

		[[params.portfolio.gallery]]
			image = "fulls/toalla3.png"
			thumb = "thumbs/toalla3.png"
			title = "Toalla Rainbow."
			description = "PAra cuando no puedes decidirte por ningún color."

		[[params.portfolio.gallery]]
			image = "fulls/toalla4.png"
			thumb = "thumbs/toalla4.png"
			title = "La tradicional arrugada."
			description = "Siempre hay alguna tolla al punto del arrastre."

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "¿Te interesan también las toallas?"
		content = "Algunas personas prefieren comprarlas al peso y otras por unidades. La verdad es que yo todavía no me he decidido!."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Inicio"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0